# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='offline_device.proto',
  package='',
  serialized_pb='\n\x14offline_device.proto\"\x19\n\tHeartbeat\x12\x0c\n\x04guid\x18\x01 \x02(\t\"\xb5\x01\n\x10SignatureRequest\x12 \n\x06wallet\x18\x01 \x02(\x0b\x32\x10.WalletIdentifer\x12-\n\x04type\x18\x02 \x02(\x0e\x32\x1f.SignatureRequest.SignatureType\x12\x0c\n\x04txDP\x18\x03 \x02(\t\x12\x1a\n\x12keepWalletUnlocked\x18\x04 \x01(\x08\"&\n\rSignatureType\x12\x0b\n\x07PARTIAL\x10\x01\x12\x08\n\x04\x46ULL\x10\x02\"!\n\x11SignatureResponse\x12\x0c\n\x04txDP\x18\x01 \x02(\t\"F\n\x13OnlineWalletRequest\x12\x13\n\x0buniqueIDB58\x18\x01 \x01(\t\x12\x1a\n\x0cmetadataOnly\x18\x02 \x01(\x08:\x04true\"6\n\x14OnlineWalletResponse\x12\x1e\n\x07wallets\x18\x01 \x03(\x0b\x32\r.OnlineWallet\"\x91\x01\n\x0cNotification\x12,\n\x04type\x18\x01 \x02(\x0e\x32\x1e.Notification.NotificationType\x12\x0f\n\x07message\x18\x02 \x02(\t\"B\n\x10NotificationType\x12\x0f\n\x0bINFORMATION\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x12\n\x0e\x43RITICAL_ERROR\x10\x03\"h\n\x0c\x43reateWallet\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0bwithEncrypt\x18\x03 \x02(\x08\x12\x0e\n\x06kdfSec\x18\x04 \x01(\x02\x12\x10\n\x08kdfBytes\x18\x05 \x01(\x02\"\x19\n\x05Reset\x12\x10\n\x08shutdown\x18\x01 \x02(\x08\"F\n\x0fWalletIdentifer\x12\x13\n\x0buniqueIDB58\x18\x01 \x02(\t\x12\x1e\n\x16lastComputedChainIndex\x18\x02 \x02(\x05\"_\n\x0cOnlineWallet\x12\x13\n\x0buniqueIDB58\x18\x01 \x02(\t\x12\x11\n\tlabelName\x18\x02 \x02(\t\x12\x12\n\nlabelDescr\x18\x03 \x02(\t\x12\x13\n\x0bpackedBytes\x18\x04 \x01(\x0c')



_SIGNATUREREQUEST_SIGNATURETYPE = descriptor.EnumDescriptor(
  name='SignatureType',
  full_name='SignatureRequest.SignatureType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='PARTIAL', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FULL', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=195,
  serialized_end=233,
)

_NOTIFICATION_NOTIFICATIONTYPE = descriptor.EnumDescriptor(
  name='NotificationType',
  full_name='Notification.NotificationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='INFORMATION', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CRITICAL_ERROR', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=478,
  serialized_end=544,
)


_HEARTBEAT = descriptor.Descriptor(
  name='Heartbeat',
  full_name='Heartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='guid', full_name='Heartbeat.guid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=49,
)


_SIGNATUREREQUEST = descriptor.Descriptor(
  name='SignatureRequest',
  full_name='SignatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='wallet', full_name='SignatureRequest.wallet', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='SignatureRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='txDP', full_name='SignatureRequest.txDP', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='keepWalletUnlocked', full_name='SignatureRequest.keepWalletUnlocked', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SIGNATUREREQUEST_SIGNATURETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=52,
  serialized_end=233,
)


_SIGNATURERESPONSE = descriptor.Descriptor(
  name='SignatureResponse',
  full_name='SignatureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='txDP', full_name='SignatureResponse.txDP', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=235,
  serialized_end=268,
)


_ONLINEWALLETREQUEST = descriptor.Descriptor(
  name='OnlineWalletRequest',
  full_name='OnlineWalletRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uniqueIDB58', full_name='OnlineWalletRequest.uniqueIDB58', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='metadataOnly', full_name='OnlineWalletRequest.metadataOnly', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=270,
  serialized_end=340,
)


_ONLINEWALLETRESPONSE = descriptor.Descriptor(
  name='OnlineWalletResponse',
  full_name='OnlineWalletResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='wallets', full_name='OnlineWalletResponse.wallets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=342,
  serialized_end=396,
)


_NOTIFICATION = descriptor.Descriptor(
  name='Notification',
  full_name='Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Notification.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='Notification.message', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NOTIFICATION_NOTIFICATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=399,
  serialized_end=544,
)


_CREATEWALLET = descriptor.Descriptor(
  name='CreateWallet',
  full_name='CreateWallet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='CreateWallet.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='CreateWallet.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='withEncrypt', full_name='CreateWallet.withEncrypt', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kdfSec', full_name='CreateWallet.kdfSec', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kdfBytes', full_name='CreateWallet.kdfBytes', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=546,
  serialized_end=650,
)


_RESET = descriptor.Descriptor(
  name='Reset',
  full_name='Reset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='shutdown', full_name='Reset.shutdown', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=652,
  serialized_end=677,
)


_WALLETIDENTIFER = descriptor.Descriptor(
  name='WalletIdentifer',
  full_name='WalletIdentifer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uniqueIDB58', full_name='WalletIdentifer.uniqueIDB58', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lastComputedChainIndex', full_name='WalletIdentifer.lastComputedChainIndex', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=679,
  serialized_end=749,
)


_ONLINEWALLET = descriptor.Descriptor(
  name='OnlineWallet',
  full_name='OnlineWallet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uniqueIDB58', full_name='OnlineWallet.uniqueIDB58', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='labelName', full_name='OnlineWallet.labelName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='labelDescr', full_name='OnlineWallet.labelDescr', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='packedBytes', full_name='OnlineWallet.packedBytes', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=751,
  serialized_end=846,
)

_SIGNATUREREQUEST.fields_by_name['wallet'].message_type = _WALLETIDENTIFER
_SIGNATUREREQUEST.fields_by_name['type'].enum_type = _SIGNATUREREQUEST_SIGNATURETYPE
_SIGNATUREREQUEST_SIGNATURETYPE.containing_type = _SIGNATUREREQUEST;
_ONLINEWALLETRESPONSE.fields_by_name['wallets'].message_type = _ONLINEWALLET
_NOTIFICATION.fields_by_name['type'].enum_type = _NOTIFICATION_NOTIFICATIONTYPE
_NOTIFICATION_NOTIFICATIONTYPE.containing_type = _NOTIFICATION;
DESCRIPTOR.message_types_by_name['Heartbeat'] = _HEARTBEAT
DESCRIPTOR.message_types_by_name['SignatureRequest'] = _SIGNATUREREQUEST
DESCRIPTOR.message_types_by_name['SignatureResponse'] = _SIGNATURERESPONSE
DESCRIPTOR.message_types_by_name['OnlineWalletRequest'] = _ONLINEWALLETREQUEST
DESCRIPTOR.message_types_by_name['OnlineWalletResponse'] = _ONLINEWALLETRESPONSE
DESCRIPTOR.message_types_by_name['Notification'] = _NOTIFICATION
DESCRIPTOR.message_types_by_name['CreateWallet'] = _CREATEWALLET
DESCRIPTOR.message_types_by_name['Reset'] = _RESET
DESCRIPTOR.message_types_by_name['WalletIdentifer'] = _WALLETIDENTIFER
DESCRIPTOR.message_types_by_name['OnlineWallet'] = _ONLINEWALLET

class Heartbeat(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEARTBEAT
  
  # @@protoc_insertion_point(class_scope:Heartbeat)

class SignatureRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNATUREREQUEST
  
  # @@protoc_insertion_point(class_scope:SignatureRequest)

class SignatureResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNATURERESPONSE
  
  # @@protoc_insertion_point(class_scope:SignatureResponse)

class OnlineWalletRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ONLINEWALLETREQUEST
  
  # @@protoc_insertion_point(class_scope:OnlineWalletRequest)

class OnlineWalletResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ONLINEWALLETRESPONSE
  
  # @@protoc_insertion_point(class_scope:OnlineWalletResponse)

class Notification(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOTIFICATION
  
  # @@protoc_insertion_point(class_scope:Notification)

class CreateWallet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEWALLET
  
  # @@protoc_insertion_point(class_scope:CreateWallet)

class Reset(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESET
  
  # @@protoc_insertion_point(class_scope:Reset)

class WalletIdentifer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WALLETIDENTIFER
  
  # @@protoc_insertion_point(class_scope:WalletIdentifer)

class OnlineWallet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ONLINEWALLET
  
  # @@protoc_insertion_point(class_scope:OnlineWallet)

# @@protoc_insertion_point(module_scope)
